name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15
          registry-url: 'https://registry.npmjs.org'

      - name: Yarn install
        run: yarn install

      - name: Runing lint, tests and make build
        run: yarn run ci

      - name: Set GIT username & email
        run: git config --global user.name 'GIT Workflow CI' && git config --global user.email dev@korniychuk.pro

      - run: npm version patch -m 'Update package version version to %s'

      - name: Generate public package.json
        run: yarn run gen-public-package.json

      - name: Generate public README.md
        run: cp README.md dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - run: npm publish --access public
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git push --no-verify & git push --tags --no-verify
